theme: jekyll-theme-architect
title: Yunxi Chen
description: Yunxi's personal website
Linkedin: "https://www.linkedin.com/in/yunxichen/"

---
layout: post
title: Awesome Blog Post
excerpt: "Why you should read my website"
tags: [intro, beginner, jekyll, tutorial]
comments: true
category: blog
---

I'm currently working on using dataframe in R to do data analysis. 
